const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

const POKEMON = {
    FETCH: 'POKEMON_FETCH',
    FETCH_ERROR: 'POKEMON_FETCH_ERROR',
    FETCH_SUCCESS: 'POKEMON_FETCH_SUCCESS'
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_POKEMONS = {
    FETCH: 'ACCOUNT_POKEMON_FETCH',
    FETCH_ERROR: 'ACCOUNT_POKEMON_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_POKEMON_FETCH_SUCCESS'
};

const ACCOUNT_INFO = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS',
}

const PUBLIC_POKEMONS = {
    FETCH: 'PUBLIC_POKEMONS_FETCH',
    FETCH_ERROR: 'PUBLIC_POKEMONS_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_POKEMONS_FETCH_SUCCESS'
};



export { GENERATION,
    POKEMON,
    ACCOUNT, 
    ACCOUNT_POKEMONS, 
    ACCOUNT_INFO, 
    PUBLIC_POKEMONS 
};
